### PR TITLE
Fixed login issue 

### PR DESCRIPTION
**Pull request by adamkdean**
Fixed public bool Login(string user, string pswd) from crashing when you give it bad credentials.

https://github.com/duncanspumpkin/Reddit-C--API/issues/1

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Thanks for the fix I don't want to merge it in until I have tested why I wrote it like that. This may take a while as I am currently changing house.

**Comment by adamkdean** [comment]
No problem. Good luck with the house move.

**Comment by adamkdean** [comment]
Hi @duncanspumpkin, hope the house move went okay.

I didn't want to bother you so I've waited 10 years.

Have you had a chance to review my PR?

If not, don't worry, you did warn that this may take a while.

See you in 2032.

**Comment by duncanspumpkin** [comment]
> Hi @duncanspumpkin, hope the house move went okay.
> 
> I didn't want to bother you so I've waited 10 years.
> 
> Have you had a chance to review my PR?
> 
> If not, don't worry, you did warn that this may take a while.
> 
> See you in 2032.

I'd be surprised if the api still works at this point. I had completely forgotten about this repo.

**Review by duncanspumpkin — APPROVED** [review]

**Comment by adamkdean** [comment]
Ha!

Me too. I just found the open PR and was shocked by the date. Thought I'd check in.

Must be one of the longest open PRs on GitHub.

**Pull request merged**
